export default [
  {
    id: 'CORE_001',
    name: 'Icky Spitter',
    cost: 0,
    power: 1,
    type: 'MINION',
    rarity: 'FREE',
  },
  {
    id: 'CORE_002',
    name: 'Rookie Lancer',
    cost: 0,
    power: 2,
    mechanic: '%ON_PLAY%',
    description: 'Give your other cards here -1 Power',
    rarity: 'FREE',
  },
  {
    id: 'CORE_003',
    name: 'Houndy Hound',
    cost: 1,
    power: 2,
    mechanic: '%ON_PLAY%',
    description: 'Draw a card from your deck',
    rarity: 'FREE',
  },
  {
    id: 'CORE_004',
    name: 'Scruffy Warrior',
    cost: 1,
    power: 2,
    mechanic: '%ON_PLAY%',
    description: 'Add a random card to your hand',
    rarity: 'FREE',
  },
  {
    id: 'CORE_005',
    name: 'Skullkid Shaman',
    cost: 1,
    power: 1,
    mechanic: '%ON_PLAY%',
    description: 'If you have 3 other cards here, +3 Power',
    rarity: 'FREE',
  },
  {
    id: 'CORE_006',
    name: 'Skilled Hunter',
    cost: 3,
    power: 1,
    mechanic: '%ON_PLAY%',
    description: 'Destroy a random enemy 1-Cost card here',
    rarity: 'FREE',
  },
  {
    id: 'CORE_007',
    name: 'Hornhat Warrior',
    cost: 3,
    power: 1,
    mechanic: '%NEXT_TURN%',
    description: 'Get +2 Power if you play a card here next turn',
    rarity: 'FREE',
  },
  {
    id: 'CORE_008',
    name: 'Faceless Witch',
    cost: 3,
    power: 1,
    mechanic: '%ON_PLAY%',
    description: "Give a random card in your opponent's hand +1 Cost",
    rarity: 'FREE',
  },
  {
    id: 'CORE_009',
    name: 'Incandescent Skeleton',
    cost: 3,
    power: 2,
    mechanic: '%ON_DEATH%',
    description: '1+ Power to all your cards if this is destroyed',
    rarity: 'SUPERIOR',
  },
  {
    id: 'CORE_010',
    name: 'Marauder',
    cost: 3,
    power: 2,
    mechanic: '%ON_PLAY%',
    description: '+2 Power if your opponent has two or more cards here',
    rarity: 'FREE',
  },
  {
    id: 'CORE_011',
    name: 'Mercenaries',
    cost: 5,
    power: 5,
    mechanic: '%ON_PLAY%',
    description: 'Add a 1/1 card to each other zone',
    rarity: 'SUPERIOR',
  },
  { id: 'CORE_011', name: 'Generic Blob', cost: 5, power: 9, rarity: 'FREE' },
  {
    id: 'CORE_012',
    name: 'Whiz Kid',
    cost: 4,
    power: -2,
    mechanic: '%ON_PLAY%',
    description: 'Add a 1/6 card to your hand',
    rarity: 'FREE',
  },
  {
    id: 'CORE_013',
    name: 'Mageman',
    cost: 4,
    power: 2,
    mechanic: '%ON_PLAY%',
    description: "Destroy the top card of your opponent's deck",
    rarity: 'FREE',
  },

  {
    id: 'CORE_014',
    name: 'Wolpertinger',
    cost: 2,
    power: 1,
    mechanic: '%EVENT%',
    description: '+2 Power when you play a card here',
    rarity: 'FREE',
  },
  {
    id: 'CORE_015',
    name: 'Obsidian Pincer',
    cost: 2,
    power: 2,
    mechanic: '%ON_PLAY%',
    description: "Put a card of your opponent's deck into your hand",
    rarity: 'FREE',
  },
  {
    id: 'CORE_016',
    name: 'Knight Lieutenant',
    cost: 2,
    power: 1,
    mechanic: '%NEXT_CARD%',
    description: 'Give the next card you play +2 Power',
    rarity: 'FREE',
  },
  {
    id: 'CORE_017',
    name: 'Nute Sprite',
    cost: 6,
    power: 2,
    mechanic: '%ON_PLAY%',
    description: 'Gain +1 total action points',
    rarity: 'FREE',
  },
  {
    id: 'CORE_018',
    name: 'Wondrous Wisp',
    cost: 6,
    power: 4,
    mechanic: '%ON_PLAY%',
    description: '+2 Power if this is at the middle zone',
    rarity: 'REMARKABLE',
  },
  {
    id: 'CORE_019',
    name: 'Volcanic Primordial',
    cost: 8,
    power: 6,
    mechanic: '%ON_PLAY%',
    description: 'Summon a 2/2 card',
    rarity: 'MYTHIC',
  },
  {
    id: 'CORE_020',
    name: 'Horrific Primordial',
    cost: 8,
    power: 3,
    rarity: 'GOLDEN',
  },
];
