const RACE = {
  NONE: '%RACE_NONE%',
  CREATURE: '%RACE_CREATURE%',
  ELEMENT: '%RACE_ELEMENT%',
  DEMONIC: '%RACE_DEMONIC%',
  ANDROID: '%RACE_ANDROID%',
  SPRITE: '%RACE_SPRITE%',
  IDOL: '%RACE_IDOL%',
  PIRATE: '%RACE_PIRATE%',
  DRAGON: '%RACE_DRAGON%',
  LOCATION: '%RACE_LOCATION%'
};

export default RACE;
