const RACE = {
  RACE_NONE: '%RACE_NONE%',
  RACE_CREATURE: '%RACE_CREATURE%',
  RACE_ELEMENT: '%RACE_ELEMENT%',
  RACE_DEMONIC: '%RACE_DEMONIC%',
  RACE_ANDROID: '%RACE_ANDROID%',
  RACE_SPRITE: '%RACE_SPRITE%',
  RACE_IDOL: '%RACE_IDOL%',
  RACE_PIRATE: '%RACE_PIRATE%',
  RACE_DRAGON: '%RACE_DRAGON%',
  RACE_LOCATION: '%RACE_LOCATION%'
};

export default RACE;
