const RARITY = {
  RARITY_NONE: '%RARITY_NONE%',
  RARITY_FREE: '%RARITY_FREE%',
  RARITY_COMMON: '%RARITY_COMMON%',
  RARITY_SUPERIOR: '%RARITY_SUPERIOR%',
  RARITY_REMARKABLE: '%RARITY_REMARKABLE%',
  RARITY_MYTHIC: '%RARITY_MYTHIC%'
};

export default RARITY;
