const RARITY = {
  NONE: '%RARITY_NONE%',
  FREE: '%RARITY_FREE%',
  COMMON: '%RARITY_COMMON%',
  SUPERIOR: '%RARITY_SUPERIOR%',
  REMARKABLE: '%RARITY_REMARKABLE%',
  MYTHIC: '%RARITY_MYTHIC%'
};

export default RARITY;
